
version: "3"
services:

  #nginx:
  #  image: nginx:latest
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
  #    - ./html:/usr/share/nginx/html
  #  networks:
  #    - link
  #  depends_on:
  #    - frontend
   
   
  frontend:
    build: ../Frontend/app
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      #- REACT_APP_BACKEND_URL=http://192.168.0.24:8080
    restart: on-failure
    networks:
      - link
    depends_on:
      - backend
  
  database:
    image: postgres:17
    environment:
      - POSTGRES_DB=mhqa_plantio
      - POSTGRES_PASSWORD=hk28gr20p1
      - POSTGRES_USER=mhqa
    ports:
      - 5432:5432
    networks:
      - link
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure   
  
  backend:
    build: ../Backend
    ports:
      - 8080:8080  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mhqa_plantio
      - SPRING_DATASOURCE_USERNAME=mhqa
      - SPRING_DATASOURCE_PASSWORD=hk28gr20p1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_APPLICATION_NAME=gerhottalica
    restart: on-failure
    networks:
      - link

networks:
   link:
     driver: bridge

volumes:
  postgres_data: